services:
  datatomb:
    build: .
    ports:
      - "8088:8088"
    volumes:
      - ./config/compose/:/usr/src/app/config/
      - datatomb-store:/tmp/datatomb
    links:
      - postgres
    env_file:
      - ./config/compose/env
    depends_on:
      - db
  db:
    image: postgres:14.2
    env_file:
      - ./config/compose/env
    ports:
      - "5432:5432"
volumes:
  datatomb-store:
