database:
  host: postgres.spang-lab.de
  database: datatomb_test
  port: 5432

server:
  port: 8088
  datasetpath: /tmp/datatomb

authserver:
  url: https://auth.spang-lab.de/api/v1
  usergroup: datatomb
  admingroup: datatombadmin
