database:
  host: postgres.spang-lab.de
  database: datatomb_test
  port: 5432

server:
  port: 8088
  datasetpath: /tmp/datatomb

authentication:
  kind: file
# only used if kind = acrux
  url: https://auth.spang-lab.de/api/v1
  usergroup: datatomb
  admingroup: datatombadmin
# only used if kind = file
  userfile: config/users.json
