apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datatomb-ingress
  namespace: data-management 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: data.spang-lab.de
    http:
      paths:
      - backend:
          serviceName: datatomb
          servicePort: 80
  tls:
  - hosts:
      - data.spang-lab.de
    secretName: data-spang-lab-tls
