apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-store-pvc
  namespace: data-management
  labels:
    app: datatomb
spec:
  storageClassName: nfs-athene
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi


